defaults:
  run:
    working-directory: api/user-api/Snap.User.API

name: Build
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: netcoreboilerplate
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_REGISTRY }}/snap-user-api:v1
        docker push ${{ secrets.ACR_REGISTRY }}/snap-user-api:v1
    - run: |
        helm registry login $ACR_NAME.azurecr.io \
          --username $USER_NAME \
          --password $PASSWORD
      env:
        ACR_NAME: ${{ secrets.ACR_REGISTRY }}
        USER_NAME: ${{ secrets.ACR_USERNAME }}
        PASSWORD: ${{ secrets.ACR_PASSWORD }}