defaults:
  run:
    working-directory: api/user-api/Snap.User.API

name: Build
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: netcoreboilerplate
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: ACR Login
      run: docker login ${{ secrets.ACR_REGISTRY }}
    - name: Build Docker Image
      run: docker build --tag snap/user-api:v1 . -t user-api
    - name: Docker Push
      run: docker push ${{ secrets.ACR_REGISTRY }}/snap/user-api:v1